version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
     
  pre_build:
    commands:
      - echo Installing source PYTHON dependencies.
      - apt-get install python3.10
      - pip install django
     
  post_build:
    

    finally:
      - python3 manage.py test
      
artifacts:
  files:
    - '**/*'
